/*
CREA LAS TABLAS POR UN ORDEN DE RELACION 
*/
CREATE TABLE MARCAS(
ID_MARCA VARCHAR(5) NOT NULL ,
DESCRIPCION VARCHAR (100),
CONSTRAINT PK_MARCAS PRIMARY KEY (ID_MARCAS)
);

CREATE TABLE TIPO_PROD(
TIPO_PROD INT  IDENTITY (1,1) NOT NULL,
DESCRIPCION VARCHAR (10),
CONSTRAINT PK_TIPOS_PRODS PRIMARY KEY (TIPO_PROD)
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT IDENTITY (1,1) NOT NULL,
TIPO_PROD INT NOT NULL,
NOMBRE  VARCHAR (50) NOT NULL,
PRECIO FLOAT (4,2),
ID_MARCA VARCHAR (5),
CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO, TIPO_PROD),
CONSTRAINT FK_PRODUCTOS_MARCAS FOREIGN KEY(ID_MARCA)
REFERENCES MARCAS (ID_MARCAS),
CONSTANT FK_PRODUCTOS_TIPOPROD FOREIGN KEY(TIPO_PRODUCTO)
REFERENCES TIPO_PROD (ID_PROD)
);

/*
AGREA ELEMENTO A LA TABLA PRODUCTO 
Y QUE NO SEA NULO 
*/
ALTER TABLE PRODUCTOS
ADD VENCIMIENTO DATE TIME NOT NULL


/*
MODIFICAR EL TIPO DE LA COMLUMNA PRECIO
*/

ALTER TABLE PRODUCTOS
ALTER COLUMN PRECIO MONEY

