/*
CREA LAS TABLAS POR UN ORDEN DE RELACION 
*/
CREATE TABLE MARCAS(
ID_MARCAS_110186 VARCHAR(5) NOT NULL ,
DESCRIPCION VARCHAR (100),
CONSTRAINT PK_MARCAS_110186 PRIMARY KEY (ID_MARCAS_110186)
);

CREATE TABLE TIPO_PROD(
TIPO_PROD_110186 INT  IDENTITY (1,1) NOT NULL,
DESCRIPCION VARCHAR (10),
CONSTRAINT PK_TIPOS_PRODS_110186 PRIMARY KEY (TIPO_PROD_110186)
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO_110186 INT IDENTITY (1,1) NOT NULL,
TIPO_PROD_110186 INT NOT NULL,
NOMBRE  VARCHAR (50) NOT NULL,
PRECIO FLOAT (4,2),
ID_MARCA VARCHAR (5),
CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO_110186 , TIPO_PROD_110186),
CONSTRAINT FK_PRODUCTOS_MARCAS_110186 FOREIGN KEY(ID_MARCA_110186)
REFERENCES MARCA (ID_MARCAS_110186),
CONSTRAINT FK_PRODUCTOS_TIPOPROD_110186 FOREIGN KEY(TIPO_PRODUCTO_110186)
REFERENCES TIPO_PROD (ID_PROD_110186)
);

/*
AGREA ELEMENTO A LA TABLA PRODUCTO 
Y QUE NO SEA NULO 
*/
ALTER TABLE PRODUCTOS
ADD VENCIMIENTO DATE TIME NOT NULL


/*
MODIFICAR EL TIPO DE LA COMLUMNA PRECIO EN TABLA PRODUCTOS
*/
ALTER TABLE PRODUCTOS
ALTER COLUMN PRECIO MONEY

/*
MODIFICAR EL TIPO DE LA COLUMNA NOMBRE EN LA TABLA PRODCUTOS
*/
ALTER TABLE PRODUCTOS
ALTER COLUMN NOMBRE VARCHAR (100)

/*
MODIFICAR ELIMINAR COLUMNA
*/
ALTER TABLE  PRODUCTOS
DROP COLUMN VENCIMIENTO
